- package-lock.json
- package.json
- src/components/Dialog.tsx
- src/components/Dialog/Curve.tsx
- src/components/Log/LogCanvas.tsx
- src/components/TriggerLog/CompositeCanvas.tsx
- src/components/TriggerLog/ToothCanvas.tsx
> Move Curve to uPlot

- src/App.tsx
- src/components/Auth/Login.tsx
- src/components/Auth/ResetPassword.tsx
- src/components/Auth/SignUp.tsx
- src/components/Auth/common.ts
- src/components/Auth/emailNotVerifiedWarning.ts
- src/components/Auth/notifications.ts
- src/components/TopBar.tsx
- src/contexts/AuthContext.tsx
- src/firebase.ts
- src/routes.ts
> Handle password reset

- src/components/Auth/Login.tsx
- src/components/Auth/ResetPassword.tsx
- src/components/Auth/SignUp.tsx
- src/components/TopBar.tsx
- src/contexts/AuthContext.tsx
- src/firebase.ts
> Add Google and Github auth providers

- src/components/Dialog.tsx
- src/components/Dialog/Curve.tsx
- src/components/Log.tsx
- src/components/SideBar.tsx
> Performance improvements

- package-lock.json
- package.json
- src/App.less
- src/pages/Upload.tsx
> Add markdown description editor

- src/pages/Upload.tsx
- src/utils/api.ts
- src/utils/logs/TriggerLogsParser.ts
- src/utils/tune/TuneParser.ts
> Validate Tune and Trigger logs before uploading

- src/App.less
- src/pages/Upload.tsx
> Upload details

- package-lock.json
- package.json
- src/App.less
- src/App.tsx
- src/components/CommandPalette.tsx
- src/components/TopBar.tsx
- src/index.tsx
- src/themes/light.less
> Command palette - initial implementation

- src/App.less
- src/components/CommandPalette.tsx
- src/components/Tune/SideBar.tsx
- src/pages/Tune.tsx
- src/themes/common.less
- src/themes/dark.less
- src/themes/light.less
> Tune in command palette

- package-lock.json
- src/types/state.ts
- src/utils/tune/TuneParser.ts
> Cleanup types, update dependencies

- src/appwrite.ts
- src/hooks/useDb.ts
- src/pages/Hub.tsx
- src/pages/Info.tsx
> Show author

- src/@types/pocketbase-types.ts
- src/hooks/useDb.ts
- src/hooks/useServerStorage.ts
- src/pages/Upload.tsx
- src/pages/auth/notifications.ts
- src/types/dbData.ts
- src/utils/api.ts
> Download official INI files

- src/App.tsx
- src/components/TopBar.tsx
- src/pages/Diagnose.tsx
- src/pages/Logs.tsx
- src/routes.ts
- src/store.ts
- src/types/state.ts
> Load user logs

- src/components/Logs/LogCanvas.tsx
- src/pages/Logs.tsx
> Show only one graph on smaller screens

- package-lock.json
- package.json
- src/pages/Logs.tsx
- src/pages/Upload.tsx
- src/utils/logs/LogParser.ts
- src/utils/logs/LogValidator.ts
- src/utils/logs/MslLogParser.ts
- src/utils/logs/TriggerLogsParser.ts
- src/workers/logParserWorker.ts
- src/workers/mlgParser.ts
- vite.config.ts
> Parse MSL logs

- index.html
- package-lock.json
- package.json
- public/manifest.json
- vite.config.ts
Rolling back #32 for the time being
> Remove PWA

- src/utils/ParserInterface.ts
- src/utils/logs/MslLogParser.ts
- src/workers/logParserWorker.ts
> Add `onProgress` for msl parsing

- src/App.tsx
- src/components/Logs/LogCanvas.tsx
- src/components/TriggerLogs/CompositeCanvas.tsx
- src/components/TriggerLogs/LogsPagination.tsx
- src/components/TriggerLogs/ToothCanvas.tsx
> Add pagination for tooth and composite logs

- src/hooks/useDb.ts
- src/pages/Hub.tsx
> Add pagination to Hub

- .github/workflows/sentry-release.yml
- src/contexts/AuthContext.tsx
- src/hooks/useDb.ts
- src/pages/Hub.tsx
- src/pocketbase.ts
- src/types/dbData.ts
- vite.config.ts
> Suppress some errors, Upload source maps to Sentry

- src/hooks/useDb.ts
- src/pages/Upload.tsx
> Autocomplete for tune attributes

- .vscode/settings.json
- src/components/TopBar.tsx
- src/hooks/useServerStorage.ts
- src/pages/auth/notifications.ts
> Download tune and logs

- package-lock.json
- package.json
- src/@types/pocketbase-types.ts
- src/contexts/AuthContext.tsx
- src/hooks/useDb.ts
- src/pages/Hub.tsx
- src/pages/Info.tsx
- src/pages/Upload.tsx
- src/pages/auth/Login.tsx
- src/pages/auth/Profile.tsx
- src/pages/auth/notifications.ts
- src/pocketbase.ts
- src/types/dbData.ts
- src/utils/time.ts
> Migrate PocketBase to new version

- src/@types/pocketbase-types.ts
- src/components/StarButton.tsx
- src/contexts/AuthContext.tsx
- src/hooks/useDb.ts
- src/pages/Hub.tsx
- src/pages/Info.tsx
> Add Stargazers
